### ISSUE TITLE
does not work correctly with input set 2 from hackerrank

### ISSUE THREAD

**Issue by acho-bacho** [RodneyShag/HackerRank_solutions#18]
https://github.com/RodneyShag/HackerRank_solutions/blob/df63989039bf20f1f59d7cd78dff610c545bc591/Algorithms/Strings/Weighted%20Uniform%20Strings/Solution.java#L25

**Comment by RodneyShag** [comment]
I just re-checked the code and it works correctly. Replace all existing Java 8 code in their editor with my code and it will work. Good luck!
